version: '3.8'

services:
  dynamodb-local:
    image: amazon/dynamodb-local:2.0.0
    container_name: scalemap-dynamodb-local
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "./data"]
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    networks:
      - scalemap-network

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:4.6.1
    container_name: scalemap-dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    depends_on:
      - dynamodb-local
    networks:
      - scalemap-network

  redis:
    image: redis:7-alpine
    container_name: scalemap-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - scalemap-network

  localstack:
    image: localstack/localstack:3.0
    container_name: scalemap-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,lambda,apigateway,cloudwatch,logs
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - localstack_data:/var/lib/localstack
    networks:
      - scalemap-network

volumes:
  dynamodb_data:
  redis_data:
  localstack_data:

networks:
  scalemap-network:
    driver: bridge